config/routes.rb
Backchannel::Application.routes.draw do
  match '/whovotedpost' => "users#whovotedpost", :via => :get
  match '/whovotedcomment' => "users#whovotedcomment", :via=> :get
  match '/admin_page'  => "admins#index", :via=> :get
  match '/admin/reports' => "admins#reports" ,:via => :get
  match '/voteforpost/incrementVote' => "posts#incrementVote", :via => :get
  match '/voteforcomment/incrementVote' => "comments#incrementVote", :via => :get
  match "/commentsforpost/new" => "comments#new" ,:via => :get
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/categories/search" => "categories#search"
  resources :comment_votes

  resources :votes

  match "/posts/new" => "posts#new"
  match "/posts/index" => "posts#index"
  match "/logins/new"   =>"logins#new"
  match "logout" => "logins#logoutUser"
  match "/users/new" => "users#new"
  match "users/show" => "users#show"
  resources :posts
  resources :admins
  resources :users
  match 'loginUser' => 'logins#loginUser'  , :via => :post
  resources :logins
  resources :comments
  resources :categories

  root :to => 'logins#new'

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logins }
    end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.json
  def new
    #@login = Logins.new
    #flash[:notice] = nil
    #respond_to do |format|
     #format.html # new.html.erb
    #format.json { render json: @login }
    #end
     session[:user_id] = nil
     session[:isadmin] = false
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  # POST /logins
  # POST /logins.json
  def loginUser
    #flash[:notice]  = "in login"   + params[:username]
    if request.post?
      session[:user_id] = User.authenticate(params[:username], params[:original_password])

      if session[:user_id] != nil
        #flash[:notice]  = "Login successful"
        #check if admin redirect to admin page
        if session[:user_id].admin == true
          session[:isadmin] =  true
          redirect_to(:controller=>:admins,:action=>:index)
        else
          #check if not admin redirect to posts
          session[:isadmin] =  false
          redirect_to(:controller=>:posts,:action=>:index)
          #redirect_to(:controller=>:logins,:action=>:new)
        end
      else
        flash[:alert] = "Login unsuccessful"
        redirect_to(:controller=>:logins,:action=>:new)
      end
    end
  end

  # PUT /logins/1
  # PUT /logins/1.json
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login = Login.find(params[:id])
    @login.destroy

    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end

  def logoutUser
    session[:user_id] = nil
    session[:isadmin]= false
    flash[:alert] = "Successfully Logged out"
    redirect_to(:controller=>:logins,:action=>:new)
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :original_password %><br />
      <%= f.text_field :original_password %>
    </div>

    <div class="actions">
      <%= f.submit "login"  %>
    </div>
    <div class="actions">
      <%= link_to "create new user" ,:controller=>'users',:action=>'new' %>
    </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logins.each do |login| %>
  <tr>
    <td><%= link_to 'Show', login %></td>
    <td><%= link_to 'Edit', edit_login_path(login) %></td>
    <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<div class="container">
  <div class="main">
    <fieldset>
      <legend>
         Log In To Backchannel
      </legend>

      <%= form_tag  '/loginUser', :method => :post%>
          <p>
            <label for="username">
              Username:
            </label>
            <%= text_field_tag :username, params[:username],:class=>"myinputs" %>
          </p>
          <p>
            <label for="original_password">
              Password:
            </label>
            <%= password_field_tag :original_password, params[:original_password],:class=>"myinputs" %>
          </p>

      <br>
      <div class="actions">
            <%= submit_tag "Login",:class=>"styled-button"%>
            &nbsp;&nbsp;&nbsp;New user?<%= link_to "Sign up" ,:controller=>'users',:action=>'new' %>
      </div>

      <%=  %>

      <% if flash[:alert] %>
          <div  style='font-color:#CC0000;font-weight:bold;'>
            <%= flash[:alert] %>
          </div>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>