config/routes.rb
Backchannel::Application.routes.draw do
  match '/whovotedpost' => "users#whovotedpost", :via => :get
  match '/whovotedcomment' => "users#whovotedcomment", :via=> :get
  match '/admin_page'  => "admins#index", :via=> :get
  match '/admin/reports' => "admins#reports" ,:via => :get
  match '/voteforpost/incrementVote' => "posts#incrementVote", :via => :get
  match '/voteforcomment/incrementVote' => "comments#incrementVote", :via => :get
  match "/commentsforpost/new" => "comments#new" ,:via => :get
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/categories/search" => "categories#search"
  resources :comment_votes

  resources :votes

  match "/posts/new" => "posts#new"
  match "/posts/index" => "posts#index"
  match "/logins/new"   =>"logins#new"
  match "logout" => "logins#logoutUser"
  match "/users/new" => "users#new"
  match "users/show" => "users#show"
  resources :posts
  resources :admins
  resources :users
  match 'loginUser' => 'logins#loginUser'  , :via => :post
  resources :logins
  resources :comments
  resources :categories

  root :to => 'logins#new'

end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :comment
  belongs_to :user
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  # GET /comment_votes
  # GET /comment_votes.json
  def index
    @comment_votes = CommentVote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comment_votes }
    end
  end

  # GET /comment_votes/1
  # GET /comment_votes/1.json
  def show
    @comment_vote = CommentVote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment_vote }
    end
  end

  # GET /comment_votes/new
  # GET /comment_votes/new.json
  def new
    @comment_vote = CommentVote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment_vote }
    end
  end

  # GET /comment_votes/1/edit
  def edit
    @comment_vote = CommentVote.find(params[:id])
  end

  # POST /comment_votes
  # POST /comment_votes.json
  def create
    @comment_vote = CommentVote.new(params[:comment_vote])

    respond_to do |format|
      if @comment_vote.save
        format.html { redirect_to @comment_vote, notice: 'Comment vote was successfully created.' }
        format.json { render json: @comment_vote, status: :created, location: @comment_vote }
      else
        format.html { render action: "new" }
        format.json { render json: @comment_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comment_votes/1
  # PUT /comment_votes/1.json
  def update
    @comment_vote = CommentVote.find(params[:id])

    respond_to do |format|
      if @comment_vote.update_attributes(params[:comment_vote])
        format.html { redirect_to @comment_vote, notice: 'Comment vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_votes/1
  # DELETE /comment_votes/1.json
  def destroy
    @comment_vote = CommentVote.find(params[:id])
    @comment_vote.destroy

    respond_to do |format|
      format.html { redirect_to comment_votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
end

app/views/comment_votes/_form.html.erb
<%if session[:user_id]!=nil%>
    <%= form_for(@comment_vote) do |f| %>
  <% if @comment_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment_vote.errors.count, "error") %> prohibited this comment_vote from being saved:</h2>

      <ul>
      <% @comment_vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/comment_votes/edit.html.erb
<%if session[:user_id]!=nil%>
    <h1>Editing comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment_vote %> |
<%= link_to 'Back', comment_votes_path %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/comment_votes/index.html.erb
<%if session[:user_id]!=nil%>
    <h1>Listing comment_votes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comment_votes.each do |comment_vote| %>
  <tr>
    <td><%= link_to 'Show', comment_vote %></td>
    <td><%= link_to 'Edit', edit_comment_vote_path(comment_vote) %></td>
    <td><%= link_to 'Destroy', comment_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment vote', new_comment_vote_path %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/comment_votes/new.html.erb
<%if session[:user_id]!=nil%>
    <h1>New comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', comment_votes_path %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/comment_votes/show.html.erb
<%if session[:user_id]!=nil%>
    <p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_vote_path(@comment_vote) %> |
<%= link_to 'Back', comment_votes_path %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>