config/routes.rb
Backchannel::Application.routes.draw do
  match '/whovotedpost' => "users#whovotedpost", :via => :get
  match '/whovotedcomment' => "users#whovotedcomment", :via=> :get
  match '/admin_page'  => "admins#index", :via=> :get
  match '/admin/reports' => "admins#reports" ,:via => :get
  match '/voteforpost/incrementVote' => "posts#incrementVote", :via => :get
  match '/voteforcomment/incrementVote' => "comments#incrementVote", :via => :get
  match "/commentsforpost/new" => "comments#new" ,:via => :get
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/categories/search" => "categories#search"
  resources :comment_votes

  resources :votes

  match "/posts/new" => "posts#new"
  match "/posts/index" => "posts#index"
  match "/logins/new"   =>"logins#new"
  match "logout" => "logins#logoutUser"
  match "/users/new" => "users#new"
  match "users/show" => "users#show"
  resources :posts
  resources :admins
  resources :users
  match 'loginUser' => 'logins#loginUser'  , :via => :post
  resources :logins
  resources :comments
  resources :categories

  root :to => 'logins#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content , :Category_id, :num_votes, :updated_at
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :votes
  has_one :category
  default_scope :order => "updated_at DESC"
  validates_presence_of :title, :content, :Category_id

  def self.destroyLinked(post)
    post.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    if params[:search] != nil
      if params[:search].to_s == "user"
           @posts = Post.find_by_sql("select * from posts where posts.User_id in (select id from users where UPPER(users.username) like UPPER('%#{params[:input]}%'))")
      elsif params[:search].to_s == "category"
           @posts = Post.find_by_sql("select * from posts where Category_id in (select id from categories where upper(name) like upper('%#{params[:input]}%'))")
      elsif params[:search].to_s == "post"
           @posts = Post.where("UPPER(content) LIKE UPPER('%#{params[:input]}%')")
      else
          @posts = Post.all
      end
    else
      @posts = Post.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def search
   @posts = Post.where("UPPER(content) LIKE UPPER('%#{params[:input]}%')")
    if @posts.length != 0
      if session[:user_id] == nil
        flash[:notice] = "Posts found are listed below:"
        respond_to do |format|
          format.html # search.html.erb
          format.json { render json: @posts }
        end
      else
          flash[:notice] = "Posts found are listed below:"
          redirect_to :controller => "posts", :action => "index", :input => params[:input], :search => :post
      end
    else
      flash[:notice] = 'No posts found for input: '+params[:input].to_s+' ! Please try again.'
      #redirect_to :controller => "posts", :action => "index"
    end
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @user = session[:user_id]
    flash[:alert] =  session[:user_id].username
    #session[:post_id]=@post.id
    if @user != nil
        flash[:alert] =  ""
        respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @post }
        end
        #redirect_to :controller => "posts", :action => "index"
    else
        flash[:alert] = "Please Login Before Posting"
        redirect_to :controller => "posts", :action => "index"
    end
   end
  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.User_id = session[:user_id].id

    respond_to do |format|
      if @post.save
        #session[:post_id] = @post.id
        #flash[:alert] = @post.id
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }

      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @post.User_id = session[:user_id].id
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])

    ###### Code block to delete the corresponding votes and comments #############

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  def incrementVote
    @post = Post.find(params[:post_id_for_vote])
    firstTimeVote = false
    if checkIfVotingAgain(params[:post_id_for_vote],session[:user_id].id) == false
      firstTimeVote = true
    else
      flash[:alert] = "Sorry. You cannot vote for a post more than once."
    end

    if session[:user_id].id == @post.User_id
      flash[:alert] = "Sorry. You cannot vote for your own post."
    end

    if session[:user_id].id != @post.User_id  and firstTimeVote == true
      #1. insert in votes
      @vote = Vote.new
      @vote.Post_id= params[:post_id_for_vote]
      @vote.User_id= session[:user_id].id   #user who voted

      @vote.save

      #2. update numvotes in Post
      @post.update_attributes(:num_votes => Integer(@post.num_votes) +1)
      flash[:alert] = "Your vote was registered successfully."
    end
    redirect_to :controller => "posts", :action => "index"
  end

  def checkIfVotingAgain(post_id,loggedin_user_id)
    @votes = Vote.all

    @votes.each do |vote|
      if  vote.User_id and  vote.Post_id
         if vote.User_id.to_s == loggedin_user_id.to_s and vote.Post_id.to_s == post_id.to_s
            return true
         end
      end
    end
    return false
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%if session[:user_id]!=nil%>
    <%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class= "field">
    <%= f.label :category %>
    <%= select("post", "Category_id", Category.all.collect{ |c| [ c.name, c.id] }) %>
  </div>
      <div class="actions">
    <%= f.submit %>
  </div>


<% end %>
  <%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/posts/edit.html.erb
<%if session[:user_id] !=nil%>
    <h1>Editing post</h1>

<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_field :content %>
    </div>
    <div class= "field">
      <%= f.label :category %>
      <%= select("post", "Category_id", Category.all.collect{ |c| [ c.name, c.id] }) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/posts/index.html.erb
<% if session[:user_id] != nil %>
    <h3><%= link_to 'Post a Question', :controller => "posts", :action => "new" %>   </h3>
    <div>
      <% if flash[:alert] %>
          <div  style="font-weight:bold;color: #cc0000;">
            <%= flash[:alert] %>
          </div>
      <% end %>
    <h1>A Brief Listing of Posts&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="position:absolute;right: 15px;"> Welcome,
      <% if session[:user_id] %>
          <%=session[:user_id].username%>!
      <%end%>
    </span></h1>
      </div>



<%  def checkDisplayComment(comment_id,loggedin_user_id)
      @votes = CommentVote.all

      @votes.each do |vote|
        if  vote.User_id and  vote.Comment_id
          if vote.User_id.to_s == loggedin_user_id.to_s and vote.Comment_id.to_s == comment_id.to_s
            return true
          end
        end
      end
      return false
    end

    def checkDisplayPost(post_id,loggedin_user_id)
      @votes = Vote.all

      @votes.each do |vote|
        if  vote.User_id and  vote.Post_id
          if vote.User_id.to_s == loggedin_user_id.to_s and vote.Post_id.to_s == post_id.to_s
            return true
          end
        end
      end
      return false
    end
%>

<% @posts.each do |post| %>

      <% @commentsForPost = Comment.find_all_by_Post_id(post.id)%>

          <div style="background-color: #00bfff;font-size:15px;">
            <b><%= post.title %>  </b>
            <td><%= link_to 'Show', post %></td>
            <% if session[:user_id].id ==post.User_id %>
            &nbsp;&nbsp;&nbsp;<td><%= link_to 'Edit', edit_post_path(post) %></td>
                <%end%>
            <% if session[:isadmin] ==true or session[:user_id].id ==post.User_id %>

                &nbsp;&nbsp;&nbsp;<td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
            &nbsp;&nbsp;&nbsp;<a href=<%="/commentsforpost/new?post_id_passed=" + post.id.to_s%>>Comment</a>
            &nbsp;&nbsp;&nbsp;<a href=<%="/voteforpost/incrementVote?post_id_for_vote=" + post.id.to_s%>>Vote</a>
            <% if checkDisplayPost(post.id,session[:user_id].id) == true %>
                <% if Integer(post.num_votes) -1 == 0 %>
                    &nbsp;&nbsp;&nbsp; You and <%= Integer(post.num_votes) -1  %>  other people voted.
                <%else%>
                    &nbsp;&nbsp;&nbsp; You and <a href=<%='/whovotedpost?post_id_voted=' + post.id.to_s %>><%= Integer(post.num_votes) -1  %></a>  other people voted.
                <% end %>
            <%else %>
                <% if Integer(post.num_votes) == 0 %>
                    &nbsp;&nbsp;&nbsp;  <%= Integer(post.num_votes)  %>  people voted.
                <% else  %>
                    &nbsp;&nbsp;&nbsp;  <a href=<%='/whovotedpost?post_id_voted=' + post.id.to_s %>><%= Integer(post.num_votes)  %></a>  people voted.
                <%end%>
             <%end%>
          </div>
          <div style="background-color: #bbffbb;">
            <%= post.content %>
              <br>
            <b>Author:</b><%= User.find(post.User_id).username %>
          </div>
        <div style="background-color: #7fffd4;">
           <b>Comments:</b>  <br>
           <% @commentsForPost.each do |comment| %>
              <%=comment.content%>
              &nbsp;&nbsp;&nbsp;Posted by:<%=User.find(comment.User_id).username%>
              <% if session[:user_id].id ==comment.User_id %>
                   &nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_comment_path(comment) %>
                  <%end%>
              <% if session[:isadmin] ==true or session[:user_id].id ==comment.User_id %>

                  &nbsp;&nbsp;&nbsp;<%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%end%>

              &nbsp;&nbsp;&nbsp;<a href=<%="/voteforcomment/incrementVote?comment_id_for_vote=" + comment.id.to_s%>>Vote</a>
              <% if checkDisplayComment(comment.id,session[:user_id].id) == true %>
                  <% if Integer(comment.num_votes) -1 == 0 %>
                    &nbsp;&nbsp;&nbsp; You and <%= Integer(comment.num_votes) -1  %> other people voted.
                  <%else%>
                    &nbsp;&nbsp;&nbsp; You and  <a href=<%='/whovotedcomment?post_id_voted=' + post.id.to_s%>><%= Integer(comment.num_votes) -1  %></a> other people voted.
                  <%end%>
              <%else %>
                  <% if Integer(comment.num_votes) == 0 %>
                    &nbsp;&nbsp;&nbsp; <%= Integer(comment.num_votes)  %>  people voted.
                  <%else%>
                      &nbsp;&nbsp;&nbsp;  <a href=<%='/whovotedcomment?post_id_voted=' + post.id.to_s%>><%= Integer(comment.num_votes)  %></a>  people voted.
                  <%end%>
              <%end%>
            <br>
           <%end%>
          </div>
        <div style="background-color:  #00bfff;">
        <span style="background-color: #dc143c; color: #ffffff; border-radius:30px;">#<%= Category.find(post.Category_id).name %> </span>
        </div>
    <hr/>


<% end %>
<br />






<%end%>

    <%if session[:user_id].nil?  %>
        <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
    <%end%>

app/views/posts/new.html.erb
<%if session[:user_id] !=nil%>
    <h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
 <%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/posts/search.html.erb
<% if session[:user_id] == nil %>
    <h2>Not logged in? <%= link_to "Login", :controller => 'logins', :action=>'new' %></h2>
    <br>
<%else%>
    <%= link_to 'Post a Question', new_post_path %>
<% end %>  <br>
<% if flash[:notice] %>
    <div  style='font-color:#CC0000;font-weight:bold; font-size: 14px;'>
      <%= flash[:notice] %>
    </div>
<% end %>


<br xmlns="http://www.w3.org/1999/html">

<!--<h4>Questions</h4> -->
<table style="width: 100%">

  <% @posts.each do |post| %>
      <% @commentsForPost = Comment.find_all_by_Post_id(post.id)%>
      <tr style="background-color: #7fffd4;">
        <td>
          <p class="title"> <b>Title:</b> <b><%= post.title %>    </b>
          &nbsp;&nbsp;&nbsp;<b><%= Integer(post.num_votes)  %></b> vote(s) received.</p>
          <p class="content"> <b>Content:</b> <%= post.content %>       </p>
          <p class="title" > <b>Author:</b>  <%= User.find(post.User_id).username %>   </p>
          <div style="background-color: #7fffd4;">
            <b>Comments (if any) :</b>  <br>
            <% @commentsForPost.each do |comment| %>
                <%=comment.content%>
                &nbsp;&nbsp;&nbsp;&nbsp;<b>Posted by: </b><%=User.find(comment.User_id).username%>
                &nbsp;&nbsp;&nbsp;&nbsp;<b><%= Integer(comment.num_votes)  %></b> vote(s) received.
            <%end%>
          </div>
          <p>
            <span style="background-color: #dc143c; color: #ffffff;">#<%= Category.find(post.Category_id).name %> </span>
          </p>


        </td>
      </tr>
  <% end %>
</table>


<br/>

app/views/posts/show.html.erb
<%if session[:user_id]!=nil%>
    <p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Category:</b>
  <%= Category.find(@post.Category_id).name %>
</p>

<p>
  <b>Author:</b>
  <%= User.find(@post.User_id).username %>
</p>


<%= link_to 'Back', posts_path %>
  <%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>