config/routes.rb
Backchannel::Application.routes.draw do
  match '/whovotedpost' => "users#whovotedpost", :via => :get
  match '/whovotedcomment' => "users#whovotedcomment", :via=> :get
  match '/admin_page'  => "admins#index", :via=> :get
  match '/admin/reports' => "admins#reports" ,:via => :get
  match '/voteforpost/incrementVote' => "posts#incrementVote", :via => :get
  match '/voteforcomment/incrementVote' => "comments#incrementVote", :via => :get
  match "/commentsforpost/new" => "comments#new" ,:via => :get
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/categories/search" => "categories#search"
  resources :comment_votes

  resources :votes

  match "/posts/new" => "posts#new"
  match "/posts/index" => "posts#index"
  match "/logins/new"   =>"logins#new"
  match "logout" => "logins#logoutUser"
  match "/users/new" => "users#new"
  match "users/show" => "users#show"
  resources :posts
  resources :admins
  resources :users
  match 'loginUser' => 'logins#loginUser'  , :via => :post
  resources :logins
  resources :comments
  resources :categories

  root :to => 'logins#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :posts, :dependent => :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def search
    #@posts = Post.find_all_by_content(params[:input])
    @posts = Post.find_by_sql("select * from posts where Category_id in (select id from categories where upper(name) like upper('%#{params[:input]}%'))")
    #@posts = Post.where("content LIKE '%#{params[:input]}%'")
    #Category.joins(:posts)
    #@categories = Category.find_all_by_name(params[:input])
    #@categories = Category.where("name LIKE '%#{params[:input]}%'")


    #@posts = Category.select("id").where(name: '(params[:input])')
    #@posts= Post.find_all_by_Category_id(LIKE (Category.select("Category_id").where(Category.find_all_by_name(params[:input]))))
    #@categories = Category.find(params[:input])
    #@cat_id = Post.where ("categories: LIKE ")
    #@posts = Post.where("Category_id LIKE @cat_id.id")#, :cat_id => '%#{ Category.fi (param[:input])}%')
    #@posts = Post.where("content LIKE ?","%"+(params[:input])+"%")
    if @posts.length != 0
        if session[:user_id] == nil
          flash[:notice] = "Posts found are listed below:"
          respond_to do |format|
            format.html # search.html.erb
            format.json { render json: @posts_search }
          end
          #redirect_to :controller => :users, :action => :search
        else
          flash[:notice] = "Posts found are listed below:"
          redirect_to :controller => "posts", :action => "index", :input => params[:input], :search => :category
     end
    else
      flash[:notice] = "No posts found for input: "+params[:input].to_s+" ! Please try again."
      #redirect_to :controller => "posts", :action => "index"
    end

  end

  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%if session[:user_id]!=nil%>
    <%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/categories/edit.html.erb
<%if session[:user_id]!=nil%>
    <h1>Editing category</h1>

<%= render 'form' %>


<%= link_to 'Back', categories_path %>
<%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/categories/index.html.erb
<%if session[:user_id]!=nil%>
    <h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    &nbsp; &nbsp;<td><%= link_to 'Show', category %></td>
    &nbsp; &nbsp;<td><%= link_to 'Edit', edit_category_path(category) %></td>
    &nbsp; &nbsp; <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Admin Home Page ', :controller => 'admins', :actions =>'index' %>
<%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/categories/new.html.erb
<%if session[:user_id]!=nil%>
    <h1>New category</h1>

<%= render 'form' %>

<%else%>

<h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>

app/views/categories/search.html.erb
<% if session[:user_id] == nil %>
    <h2>Not logged in? <%= link_to "Login", :controller => 'logins', :action=>'new' %></h2>
    <br>
    <%else%>
    <%= link_to 'Post a Question', new_post_path %>
<% end %>  <br>
<% if flash[:notice] %>
    <div  style='font-color:#CC0000;font-weight:bold; font-size: 14px;'>
      <%= flash[:notice] %>
    </div>
<% end %>

<br>

<table style="width: 100%">

  <% @posts.each do |post| %>
      <% @commentsForPost = Comment.find_all_by_Post_id(post.id)%>
      <tr style="background-color: #7fffd4;">
        <td>
          <p class="title"> <b>Title:</b> <b><%= post.title %> </b>
          &nbsp;&nbsp;&nbsp;<b><%= Integer(post.num_votes)  %></b> vote(s) received.</p>
          <p class="content"> <b>Content:</b> <%= post.content %>    </p>
          <p class="title" > <b>Author:</b>  <%= User.find(post.User_id).username %>   </p>
          <div style="background-color: #7fffd4;">
            <b>Comments (if any) :</b>  <br>
            <% @commentsForPost.each do |comment| %>
                <%=comment.content%>
                &nbsp;&nbsp;&nbsp;&nbsp;<b>Posted by: </b><%=User.find(comment.User_id).username%>
                &nbsp;&nbsp;&nbsp;&nbsp;<b><%= Integer(comment.num_votes)  %></b> vote(s) received.
            <%end%>
          </div>
          <p>
            <span style="background-color: #dc143c; color: #ffffff;">#<%= Category.find(post.Category_id).name %> </span>
          </p>

        </td>
      </tr>
  <% end %>
</table>


<br/>

app/views/categories/show.html.erb
<%if session[:user_id]!=nil%>
    <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'admin home page', :controller => 'admins', :action => 'index' %>
<%else%>

    <h2>Please log in <%= link_to "here", :controller => 'logins', :action=>'new' %></h2>
<%end%>